params ["_logibox"];
systemChat "Making an full Resupply Crate, Plaese wait.";
_BaseboxBigpawn = [[_logibox, "TOP"], "BL_Crate_D207_OpDem", 1, [0,5,0], (0),{0},false] call BIS_fnc_spawnObjects;
_BaseboxBig = _BaseboxBigpawn select 0;
[_BaseboxBig, 20] call ace_cargo_fnc_setSpace;
_Resupply1 = [_BaseboxBig] spawn D207_fnc_OpAlpha;
_Resupply2 = [_BaseboxBig] spawn D207_fnc_OpBravo;
_Resupply3 = [_BaseboxBig] spawn D207_fnc_OpCharlie;
_Resupply4 = [_BaseboxBig] spawn D207_fnc_OpReaper;
_Resupply5 = [_BaseboxBig] spawn D207_fnc_OpPHQ;
waitUntil {scriptDone _Resupply1};
waitUntil {scriptDone _Resupply2};
waitUntil {scriptDone _Resupply3};
waitUntil {scriptDone _Resupply4};
waitUntil {scriptDone _Resupply5};
_BaseboxBig allowDamage false;
_BaseboxBig enableSimulation true;
_Wheel = "UGV_02_Wheel_F" createVehicle position player;
_Wheelpos = getPos _Wheel;
deleteVehicle _Wheel;
_BaseboxBig setPos _Wheelpos;
_BaseboxBig allowDamage true;
systemChat "A full Resupply has been made and loaded in the spawned Crate near you.";