private ["_box"];
_box = nearestObject [player,"ReammoBox_F"];
_Medbox = getPos _box;
_Playerdir = vectorDir player;
_Playerdirx = [];
_Playerdiry = [];
_Playerdirx = _Playerdir select 0;
_Playerdiry = _Playerdir select 1;
_Playerdirx = round _Playerdirx;
_Playerdiry = round _Playerdiry;
_DIRway = 0;
_oldrespawn = getMarkerPos "respawn";
_oldrespawnObjects = nearestObjects [_oldrespawn, ["Strategic"], 5];
{
	if (typeOf _x == "Land_BagFence_Long_F") then {deleteVehicle _x;};
} foreach _oldrespawnObjects;
if (_Playerdirx == 1 && _Playerdiry == 1) then {_makernum = floor (random 2); if (_makernum == 1) then {_DIRway = 1;} else {_DIRway = 2;};};
if (_Playerdirx == 1 && _Playerdiry == -1) then {_makernum = floor (random 2); if (_makernum == 1) then {_DIRway = 2;} else {_DIRway = 3;};};
if (_Playerdirx == -1 && _Playerdiry == -1) then {_makernum = floor (random 2); if (_makernum == 1) then {_DIRway = 3;} else {_DIRway = 4;};};
if (_Playerdirx == -1 && _Playerdiry == 1) then {_makernum = floor (random 2); if (_makernum == 1) then {_DIRway = 4;} else {_DIRway = 1;};};
if (_Playerdirx == 0 && _Playerdiry == 1) then {_DIRway = 1;};
if (_Playerdirx == 1 && _Playerdiry == 0) then {_DIRway = 2;};
if (_Playerdirx == 0 && _Playerdiry == -1) then {_DIRway = 3;};
if (_Playerdirx == -1 && _Playerdiry == 0) then {_DIRway = 4;};
_fence1 = [];
_fence2 = [];
_fence3 = [];
_fence4 = [];
_fence5 = [];
_fence6 = [];
_fence7 = [];
_fence8 = [];
_markerpos = [];
_Medboxx = _Medbox select 0;
_Medboxy = _Medbox select 1;
_fence1 set [0, _Medboxx - 3];
_fence1 set [1, _Medboxy - 1.5];
_fence2 set [0, _Medboxx - 3];
_fence2 set [1, _Medboxy + 1.5];
_fence3 set [0, _Medboxx - 1.5];
_fence3 set [1, _Medboxy + 3];
_fence4 set [0, _Medboxx + 1.5];
_fence4 set [1, _Medboxy + 3];
_fence5 set [0, _Medboxx + 3];
_fence5 set [1, _Medboxy + 1.5];
_fence6 set [0, _Medboxx + 3];
_fence6 set [1, _Medboxy - 1.5];
_fence7 set [0, _Medboxx - 1.5];
_fence7 set [1, _Medboxy - 3];
_fence8 set [0, _Medboxx + 1.5];
_fence8 set [1, _Medboxy - 3];
_markerpos set [0, _Medboxx];
_markerpos set [1, _Medboxy];
deleteVehicle _box;
_marker1 = createMarker ["Tempmarkermove", _markerpos];
_bfence1 = createVehicle ["Land_BagFence_Long_F",_fence1,[],0,"CAN_COLLIDE"];
_bfence2 = createVehicle ["Land_BagFence_Long_F",_fence2,[],0,"CAN_COLLIDE"];
_bfence3 = createVehicle ["Land_BagFence_Long_F",_fence3,[],0,"CAN_COLLIDE"];
_bfence4 = createVehicle ["Land_BagFence_Long_F",_fence4,[],0,"CAN_COLLIDE"];
_bfence5 = createVehicle ["Land_BagFence_Long_F",_fence5,[],0,"CAN_COLLIDE"];
_bfence6 = createVehicle ["Land_BagFence_Long_F",_fence6,[],0,"CAN_COLLIDE"];
_bfence7 = createVehicle ["Land_BagFence_Long_F",_fence7,[],0,"CAN_COLLIDE"];
_bfence8 = createVehicle ["Land_BagFence_Long_F",_fence8,[],0,"CAN_COLLIDE"];
_bfence1 setDir 90;
_bfence2 setDir 270;
_bfence3 setDir 180;
_bfence4 setDir 0;
_bfence5 setDir 270;
_bfence6 setDir 90;
_bfence7 setDir 180;
_bfence8 setDir 0;
"respawn" setmarkerpos getmarkerpos "Tempmarkermove";
Respawntrigger setPos getmarkerpos "Tempmarkermove";
if (_DIRway == 1) then {deleteVehicle _bfence7;deleteVehicle _bfence8;"respawn" setMarkerDir 180;Respawntrigger setDir 180;systemChat "Player respawn has been moved!";};
if (_DIRway == 2) then {deleteVehicle _bfence1;deleteVehicle _bfence2;"respawn" setMarkerDir 270;Respawntrigger setDir 270;systemChat "Player respawn has been moved!";};
if (_DIRway == 3) then {deleteVehicle _bfence3;deleteVehicle _bfence4;"respawn" setMarkerDir 0;Respawntrigger setDir 0;systemChat "Player respawn has been moved!";};
if (_DIRway == 4) then {deleteVehicle _bfence5;deleteVehicle _bfence6;"respawn" setMarkerDir 90;Respawntrigger setDir 90;systemChat "Player respawn has been moved!";};
deleteMarker "Tempmarkermove";