_Platoon = "cannot";
_Foxtrot = "cannot";
_Hawkeye = "cannot";
_Drone = "cannot";
if !(D207_VehiclePlatoon) then {_Platoon = "can";};
if !(D207_VehicleFoxtrot) then {_Foxtrot = "can";};
if !(D207_VehicleHawkeye) then {_Hawkeye = "can";};
if !(D207_VehicleDrone) then {_Drone = "can";};
_hinttext1 = parseText format ["You %1 spawn Platoon Vehicle's.", _Platoon];
_hinttext2 = parseText format ["You %1 spawn Foxtrot Vehicle's.", _Foxtrot];
_hinttext3 = parseText format ["You %1 spawn Hawkeye Vehicle's.", _Hawkeye];
_hinttext4 = parseText format ["You %1 spawn Hawkeye Vehicle's.", _Drone];
hint composeText [_hinttext1, lineBreak, _hinttext2, lineBreak, _hinttext3, lineBreak, _hinttext4];
_ctrlPLT = (findDisplay 8000) displayCtrl 1601;
_ctrlFOX = (findDisplay 8000) displayCtrl 1602;
_ctrlHAW = (findDisplay 8000) displayCtrl 1603;
_ctrlDrone = (findDisplay 8000) displayCtrl 1603;
if (D207_VehiclePlatoon) then {_ctrlPLT ctrlSetBackgroundColor [0.7, 0, 0, 0.5];} else {_ctrlPLT ctrlSetBackgroundColor [0, 0.7, 0, 0.5];};
if (D207_VehicleFoxtrot) then {_ctrlFOX ctrlSetBackgroundColor [0.7, 0, 0, 0.5];} else {_ctrlFOX ctrlSetBackgroundColor [0, 0.7, 0, 0.5];};
if (D207_VehicleHawkeye) then {_ctrlHAW ctrlSetBackgroundColor [0.7, 0, 0, 0.5];} else {_ctrlHAW ctrlSetBackgroundColor [0, 0.7, 0, 0.5];};
if (D207_VehicleDrone) then {_ctrlDrone ctrlSetBackgroundColor [0.7, 0, 0, 0.5];} else {_ctrlDrone ctrlSetBackgroundColor [0, 0.7, 0, 0.5];};