params ["_EndExPos"];
EndExPos = _EndExPos;
publicVariable "EndExPos";
_flagPos1 = [(_EndExPos select 0) + 20, _EndExPos select 1, _EndExPos select 2];
_flagPos2 = [(_EndExPos select 0) - 20, _EndExPos select 1, _EndExPos select 2];
_flag1 = "FLAG_adfrc_F" createVehicle _flagPos1;
_flag2 = "FLAG_adfrc_F" createVehicle _flagPos2;
_boxPos1 = [(_EndExPos select 0) + 5, (_EndExPos select 1) + 2, _EndExPos select 2];
_boxPos2 = [(_EndExPos select 0) - 5, (_EndExPos select 1) + 2, _EndExPos select 2];
_box1 = "C_IDAP_supplyCrate_F" createVehicle _boxPos1;
_box2 = "C_IDAP_supplyCrate_F" createVehicle _boxPos2;
clearItemCargoGlobal _box1;
clearMagazineCargoGlobal _box1;
clearBackpackCargoGlobal _box1;
clearWeaponCargoGlobal _box1;
clearItemCargoGlobal _box2;
clearMagazineCargoGlobal _box2;
clearBackpackCargoGlobal _box2;
clearWeaponCargoGlobal _box2;
_box1 addItemCargoGlobal ["J_207_Beret", 60];
_box1 addItemCargoGlobal ["O_207_Beret", 60];
_box1 addItemCargoGlobal ["V_207_Beret", 60];
_box2 addItemCargoGlobal ["J_207_Beret", 60];
_box2 addItemCargoGlobal ["O_207_Beret", 60];
_box2 addItemCargoGlobal ["V_207_Beret", 60];
_EndExmarker = createMarker ["EndEx", _EndExPos];
_EndExmarker setMarkerType "mil_flag";
_EndExmarker setMarkerText "EndEx LOC";
_EndExmarker setMarkerColor "#(0.1255,0.4471,0.0275)";
missionNamespace setVariable ["endex", true, true];