private ["_thisTrigger"];
params ["_thisTrigger"];
_playersingtrgg = allPlayers inAreaArray _thisTrigger;
_playrtoping = _playersingtrgg select 0;
_Pname = name _playrtoping;
private _playrping = parseText format ["<t size='1.25' color='#ff0000'>A ping has been sent, Please wait next to the sign for a Hawkeye pilot"];
_playrping remoteExec ["hint", _playrtoping];
private _callteext = parseText format ["<t size='1.25' color='#ff0000'>%1 is waiting for reinsertion from Base", _Pname]; 
_Pingteam = ["BZ1","BZ2","B1PHQ","B5PHQ","BHEC","BHE2","BHES","RZ1","RZ2","R1PHQ","R5PHQ","RHEC","RHE2","RHES","GZ1","GZ2","G1PHQ","G5PHQ","GHEC","GHE2","GHES"]; 
_callteext remoteExec ["hint", _Pingteam];