params ["_mainbox"];
_mainbox enableSimulation false;
[parseText "<t align='center' shadow='2' size='4'><t color='#2e2790'>Unpacking sandbags</t></t><br/>", [0,0.7,1,0.5], nil, 7, 0.7, 0] spawn BIS_fnc_textTiles;
sleep 1;
_sandbagL = [[_mainbox, "GROUND"], "Land_BagFence_Round_F", 1, [1.5,0,0], (270),{0},true] call BIS_fnc_spawnObjects;
sleep 1;
_sandbagR = [[_mainbox, "GROUND"], "Land_BagFence_Round_F", 1, [-1.5,0,0], (90),{0},true] call BIS_fnc_spawnObjects;
sleep 1;
_sandbagF = [[_mainbox, "GROUND"], "Land_BagFence_Round_F", 1, [0,1.5,0], (180),{0},true] call BIS_fnc_spawnObjects;
sleep 1;
[parseText "<t align='center' shadow='2' size='4'><t color='#2e2790'>Unpacking M2HB-QCB High</t></t><br/>", [0,0.7,1,0.5], nil, 7, 0.7, 0] spawn BIS_fnc_textTiles;
_Mortar = [[_mainbox, "GROUND"], "ADFRC_m2qcb_high", 1, [0.25,0,0], 0,{0},false] call BIS_fnc_spawnObjects;
sleep 2;
[parseText "<t align='center' shadow='2' size='4'><t color='#2e2790'>Unpacking M2HB-QCB High Ammo</t></t><br/>", [0,0.7,1,0.5], nil, 7, 0.7, 0] spawn BIS_fnc_textTiles;
_MortarAmmos = [[_mainbox, "GROUND"], "ACE_Box_82mm_Mo_HE", 1, [1,-1.75,0], 0,{0},true] call BIS_fnc_spawnObjects;
deleteVehicle _mainbox;
sleep 2;
_MortarAmmo = _MortarAmmos select 0;
_Mortar select 0 enableSimulation true;
clearItemCargoGlobal _MortarAmmo;
clearMagazineCargoGlobal _MortarAmmo;
clearBackpackCargoGlobal _MortarAmmo;
clearWeaponCargoGlobal _MortarAmmo;
_MortarAmmo addItemCargoGlobal ["ace_csw_100Rnd_127x99_mag", 8];
sleep 2;
_delammo = _Mortar select 0 nearSupplies 5;
{
if (typeOf _x == "ace_csw_ammo_holder") then {deleteVehicle _x;};
} forEach _delammo;
[parseText "<t align='center' shadow='2' size='4'><t color='#2e2790'>M2HB-QCB High has been unpacked</t></t><br/>", [0,0.7,1,0.5], nil, 7, 0.7, 0] spawn BIS_fnc_textTiles;