private ["_Arsenalbox"];
params ["_Arsenalbox"];
_Arsenalbox = _this select 0;
if (hasInterface) then {
	[_Arsenalbox, true, false] call ace_arsenal_fnc_removeVirtualItems;
	hint "Updating Arsenal, Please wait";
	sleep 5;
	[_Arsenalbox, [],true] call ace_arsenal_fnc_initBox;
	[_Arsenalbox, D207_guns,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Handgun,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_lunchers,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_unf,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Vests,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Backpacks,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Hats,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_eyewear,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Atmet,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Ammo,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Gen,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Med,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Mines,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_misc,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_PHat,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Medlvl1,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Medlvl2,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_EOD,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_ENGLVL1,true] call ace_arsenal_fnc_addVirtualItems;
	[_Arsenalbox, D207_Drones,true] call ace_arsenal_fnc_addVirtualItems;
	hint "Arsenal updated";
	sleep 15;
	hintSilent "";
};
